---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec: 
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: qtdevops
            - name: MYSQL_PASSWORD
              value: manojdevops  
              valueFrom:
                secretKeyRef:
                  name: openmrs
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim                                    